import {
  Organization,
  Company,
  Branch,
  Location,
  Department,
  Designation,
  Role,
  User,
  Employee,
  ApprovalItem,
  ActivityItem,
  DashboardMetrics,
} from '../types';

export const initialOrganization: Organization = {
  id: 'org-acme-01',
  name: 'Acme Global Enterprise',
  industry: 'Software & Technology Services',
  default_currency: 'USD',
  timezone: 'Asia/Kolkata',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2026-08-11T00:00:00Z',
};

export const initialCompanies: Company[] = [
  {
    id: 'comp-01',
    organization_id: 'org-acme-01',
    legal_name: 'Acme Technologies Pvt Ltd',
    trade_name: 'AcmeTech India',
    statutory_registration_no: 'CIN-U72200TZ2020PTC034120',
    tax_id: 'PAN-AAACA1234F',
    country: 'India',
    city: 'Coimbatore',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'comp-02',
    organization_id: 'org-acme-01',
    legal_name: 'Acme Innovations Inc',
    trade_name: 'Acme US',
    statutory_registration_no: 'DE-FEIN-987654321',
    tax_id: 'EIN-987654321',
    country: 'United States',
    city: 'San Jose',
    created_at: '2024-03-01T00:00:00Z',
  },
];

export const initialBranches: Branch[] = [
  {
    id: 'br-cbe',
    company_id: 'comp-01',
    name: 'Coimbatore Main Campus',
    code: 'BR-CBE',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    timezone: 'Asia/Kolkata',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'br-blr',
    company_id: 'comp-01',
    name: 'Bengaluru Tech Hub',
    code: 'BR-BLR',
    city: 'Bengaluru',
    state: 'Karnataka',
    timezone: 'Asia/Kolkata',
    created_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'br-sjc',
    company_id: 'comp-02',
    name: 'San Jose HQ',
    code: 'BR-SJC',
    city: 'San Jose',
    state: 'California',
    timezone: 'America/Los_Angeles',
    created_at: '2024-03-01T00:00:00Z',
  },
];

export const initialLocations: Location[] = [
  {
    id: 'loc-cbe-01',
    branch_id: 'br-cbe',
    name: 'TIDEL Park Office - Phase II',
    building: 'Module 402, 4th Floor',
    address: 'ELCOCT SEZ, Civil Aerodrome Post, Coimbatore, TN 641014',
  },
  {
    id: 'loc-blr-01',
    branch_id: 'br-blr',
    name: 'Manyata Embassy Business Park',
    building: 'Tower 7, 3rd Floor',
    address: 'Outer Ring Rd, Nagavara, Bengaluru, KA 560045',
  },
];

export const initialDepartments: Department[] = [
  {
    id: 'dept-eng',
    company_id: 'comp-01',
    name: 'Engineering',
    code: 'ENG',
    head_employee_id: 'emp-001',
    employee_count: 185,
  },
  {
    id: 'dept-pd',
    company_id: 'comp-01',
    name: 'Product & Design',
    code: 'PD',
    head_employee_id: 'emp-002',
    employee_count: 42,
  },
  {
    id: 'dept-hr',
    company_id: 'comp-01',
    name: 'Human Resources',
    code: 'HR',
    head_employee_id: 'emp-003',
    employee_count: 16,
  },
  {
    id: 'dept-fin',
    company_id: 'comp-01',
    name: 'Finance & Payroll',
    code: 'FIN',
    head_employee_id: 'emp-004',
    employee_count: 12,
  },
  {
    id: 'dept-ops',
    company_id: 'comp-01',
    name: 'Operations & IT',
    code: 'OPS',
    head_employee_id: 'emp-005',
    employee_count: 24,
  },
];

export const initialDesignations: Designation[] = [
  {
    id: 'desig-ceo',
    company_id: 'comp-01',
    title: 'Chief Executive Officer',
    code: 'EXEC-01',
    grade: 'L8',
  },
  {
    id: 'desig-hrhead',
    company_id: 'comp-01',
    title: 'Head of Human Resources',
    code: 'HR-01',
    grade: 'L7',
  },
  {
    id: 'desig-engmgr',
    company_id: 'comp-01',
    title: 'Senior Engineering Manager',
    code: 'ENG-02',
    grade: 'L6',
  },
  {
    id: 'desig-staffeng',
    company_id: 'comp-01',
    title: 'Staff Frontend Engineer',
    code: 'ENG-03',
    grade: 'L5',
  },
  {
    id: 'desig-srdes',
    company_id: 'comp-01',
    title: 'Senior Product Designer',
    code: 'PD-02',
    grade: 'L4',
  },
  {
    id: 'desig-hradmin',
    company_id: 'comp-01',
    title: 'HR Operations Lead',
    code: 'HR-03',
    grade: 'L3',
  },
  {
    id: 'desig-srfin',
    company_id: 'comp-01',
    title: 'Senior Payroll Specialist',
    code: 'FIN-02',
    grade: 'L4',
  },
];

export const initialRoles: Role[] = [
  {
    id: 'role-superadmin',
    organization_id: 'org-acme-01',
    name: 'Super Admin',
    description: 'Full cross-tenant platform administration and policy configuration.',
    is_system: true,
    permissions: [
      { permission_id: 'perm-all', scope_level: 'org' },
    ],
  },
  {
    id: 'role-companyadmin',
    organization_id: 'org-acme-01',
    name: 'Company Admin',
    description: 'Full operational access across legal entities, branches, and departments.',
    is_system: true,
    permissions: [
      { permission_id: 'perm-people-all', scope_level: 'company' },
      { permission_id: 'perm-org-all', scope_level: 'company' },
      { permission_id: 'perm-rbac-all', scope_level: 'company' },
    ],
  },
  {
    id: 'role-hrhead',
    organization_id: 'org-acme-01',
    name: 'HR Head',
    description: 'Oversees people policy, strategic headcount, escalations, and compliance.',
    is_system: true,
    permissions: [
      { permission_id: 'perm-people-manage', scope_level: 'company' },
      { permission_id: 'perm-leave-approve', scope_level: 'company' },
    ],
  },
  {
    id: 'role-manager',
    organization_id: 'org-acme-01',
    name: 'Manager',
    description: 'Direct reporting line oversight, leave/expense approvals, and team reviews.',
    is_system: true,
    permissions: [
      { permission_id: 'perm-people-view', scope_level: 'manager' },
      { permission_id: 'perm-leave-approve', scope_level: 'manager' },
    ],
  },
  {
    id: 'role-employee',
    organization_id: 'org-acme-01',
    name: 'Employee',
    description: 'Self-service workspace, personal profile, leave application, and documents.',
    is_system: true,
    permissions: [
      { permission_id: 'perm-self-view', scope_level: 'self' },
    ],
  },
  {
    id: 'role-teamlead',
    organization_id: 'org-acme-01',
    name: 'Team Lead',
    description: 'Direct team operations, peer feedback, shift clocking, and initial approvals.',
    is_system: true,
    permissions: [
      { permission_id: 'perm-people-view', scope_level: 'dept' },
      { permission_id: 'perm-leave-approve', scope_level: 'dept' },
    ],
  },
];

export const initialUsers: User[] = [
  {
    id: 'user-super-01',
    organization_id: 'org-acme-01',
    email: 'superadmin@workforceos.com',
    name: 'Arun Kumar',
    avatar_url: '',
    employee_id: 'emp-000',
    status: 'Active',
    roles: [initialRoles[0]], // Super Admin
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-001',
    organization_id: 'org-acme-01',
    email: 'admin@acme.com',
    name: 'Dharun Joy (Company Admin)',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    employee_id: 'emp-001',
    status: 'Active',
    roles: [initialRoles[1]], // Company Admin
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user-003',
    organization_id: 'org-acme-01',
    email: 'arun.kumar@acme.com',
    name: 'Arun Kumar (HR Head)',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    employee_id: 'emp-003',
    status: 'Active',
    roles: [initialRoles[2]], // HR Head
    created_at: '2024-01-18T00:00:00Z',
  },
  {
    id: 'user-004',
    organization_id: 'org-acme-01',
    email: 'karthik.n@acme.com',
    name: 'Karthik N. (Engineering Manager)',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    employee_id: 'emp-002',
    status: 'Active',
    roles: [initialRoles[3]], // Manager
    created_at: '2024-01-19T00:00:00Z',
  },
  {
    id: 'user-005',
    organization_id: 'org-acme-01',
    email: 'deepa.s@acme.com',
    name: 'Deepa S. (Lead Architect / Team Lead)',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    employee_id: 'emp-005',
    status: 'Active',
    roles: [initialRoles[5]], // Team Lead
    created_at: '2024-01-21T00:00:00Z',
  },
  {
    id: 'user-002',
    organization_id: 'org-acme-01',
    email: 'priya.sharma@acme.com',
    name: 'Priya Sharma (Senior Product Designer)',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    employee_id: 'emp-1024',
    status: 'Active',
    roles: [initialRoles[4]], // Employee
    created_at: '2024-01-20T00:00:00Z',
  },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1024',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-cbe',
    branch_name: 'Coimbatore Main Campus',
    department_id: 'dept-pd',
    department_name: 'Product & Design',
    designation_id: 'desig-srdes',
    designation_title: 'Senior Product Designer',
    user_id: 'user-002',
    employee_code: 'EMP-1024',
    first_name: 'Priya',
    last_name: 'Sharma',
    work_email: 'priya.sharma@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 98765 43210',
      personal_email: 'priya.sharma.ux@gmail.com',
      date_of_birth: '1995-06-14',
      gender: 'Female',
      national_id_masked: '•••• •••• 8821',
      emergency_contact_name: 'Rajesh Sharma',
      emergency_contact_phone: '+91 98123 45678',
      address: '42 Avinashi Road, Race Course, Coimbatore, TN 641018',
      bank_account_masked: '•••• •••• 4492',
      bank_name: 'HDFC Bank Ltd',
    },
    employment: {
      doj: '2024-01-12',
      reporting_manager_id: 'emp-002',
      reporting_manager_name: 'Arun Kumar',
      probation_end_date: '2024-07-12',
      notice_period_days: 60,
      work_location: 'Coimbatore SEZ',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 1850000,
    },
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-001',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-cbe',
    branch_name: 'Coimbatore Main Campus',
    department_id: 'dept-eng',
    department_name: 'Engineering',
    designation_id: 'desig-engmgr',
    designation_title: 'Senior Engineering Manager',
    user_id: 'user-001',
    employee_code: 'EMP-001',
    first_name: 'Dharun',
    last_name: 'Joy',
    work_email: 'dharun.joy@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 91234 56789',
      personal_email: 'dharun.joy@gmail.com',
      date_of_birth: '1990-03-22',
      gender: 'Male',
      national_id_masked: '•••• •••• 1209',
      emergency_contact_name: 'Sarah Joy',
      emergency_contact_phone: '+91 91234 99999',
      address: '108 Trichy Road, Singanallur, Coimbatore, TN 641005',
      bank_account_masked: '•••• •••• 9012',
      bank_name: 'ICICI Bank Ltd',
    },
    employment: {
      doj: '2023-06-01',
      reporting_manager_id: null,
      reporting_manager_name: 'Executive Board',
      notice_period_days: 90,
      work_location: 'Coimbatore Main Campus',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 3200000,
    },
    created_at: '2023-06-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-002',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-blr',
    branch_name: 'Bengaluru Tech Hub',
    department_id: 'dept-pd',
    department_name: 'Product & Design',
    designation_id: 'desig-srdes',
    designation_title: 'VP of Product',
    employee_code: 'EMP-002',
    first_name: 'Rahul',
    last_name: 'Menon',
    work_email: 'rahul.menon@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 99887 76655',
      personal_email: 'rahul.m@gmail.com',
      date_of_birth: '1988-11-05',
      gender: 'Male',
      national_id_masked: '•••• •••• 4511',
      emergency_contact_name: 'Anitha Menon',
      emergency_contact_phone: '+91 99887 11111',
      address: 'Indiranagar 100ft Road, Bengaluru, KA 560038',
      bank_account_masked: '•••• •••• 1122',
      bank_name: 'Axis Bank Ltd',
    },
    employment: {
      doj: '2023-08-15',
      reporting_manager_id: 'emp-001',
      reporting_manager_name: 'Dharun Joy',
      notice_period_days: 90,
      work_location: 'Bengaluru Tech Hub',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 2800000,
    },
    created_at: '2023-08-15T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-003',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-cbe',
    branch_name: 'Coimbatore Main Campus',
    department_id: 'dept-hr',
    department_name: 'Human Resources',
    designation_id: 'desig-hrhead',
    designation_title: 'Head of Human Resources',
    user_id: 'user-003',
    employee_code: 'EMP-003',
    first_name: 'Arun',
    last_name: 'Kumar',
    work_email: 'arun.kumar@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 97766 55443',
      personal_email: 'arunkumar.hr@gmail.com',
      date_of_birth: '1987-09-18',
      gender: 'Male',
      national_id_masked: '•••• •••• 7732',
      address: 'RS Puram, Coimbatore, TN 641002',
    },
    employment: {
      doj: '2023-09-01',
      reporting_manager_id: 'emp-001',
      reporting_manager_name: 'Dharun Joy',
      notice_period_days: 90,
      work_location: 'Coimbatore Main Campus',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 2600000,
    },
    created_at: '2023-09-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-004',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-blr',
    branch_name: 'Bengaluru Tech Hub',
    department_id: 'dept-eng',
    department_name: 'Engineering',
    designation_id: 'desig-staffeng',
    designation_title: 'Staff Frontend Engineer',
    employee_code: 'EMP-1025',
    first_name: 'Ananya',
    last_name: 'Reddy',
    work_email: 'ananya.reddy@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    status: 'Probation',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 96655 44332',
      personal_email: 'ananyareddy.code@gmail.com',
      date_of_birth: '1997-01-30',
      gender: 'Female',
    },
    employment: {
      doj: '2026-05-15',
      reporting_manager_id: 'emp-001',
      reporting_manager_name: 'Dharun Joy',
      probation_end_date: '2026-11-15',
      notice_period_days: 60,
      work_location: 'Bengaluru Tech Hub',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 2100000,
    },
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-005',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-cbe',
    branch_name: 'Coimbatore Main Campus',
    department_id: 'dept-fin',
    department_name: 'Finance & Payroll',
    designation_id: 'desig-srfin',
    designation_title: 'Senior Payroll Specialist',
    employee_code: 'EMP-1026',
    first_name: 'Vikram',
    last_name: 'Srinivasan',
    work_email: 'vikram.s@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 95544 33221',
      personal_email: 'vikram.fin@gmail.com',
    },
    employment: {
      doj: '2024-02-01',
      reporting_manager_id: 'emp-003',
      reporting_manager_name: 'Arun Kumar',
      notice_period_days: 60,
      work_location: 'Coimbatore Main Campus',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 1400000,
    },
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-006',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-cbe',
    branch_name: 'Coimbatore Main Campus',
    department_id: 'dept-eng',
    department_name: 'Engineering',
    designation_id: 'desig-staffeng',
    designation_title: 'Senior DevOps Architect',
    employee_code: 'EMP-1027',
    first_name: 'Karthik',
    last_name: 'Raja',
    work_email: 'karthik.raja@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    status: 'Notice Period',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 94433 22110',
    },
    employment: {
      doj: '2023-11-01',
      reporting_manager_id: 'emp-001',
      reporting_manager_name: 'Dharun Joy',
      notice_period_days: 60,
      work_location: 'Coimbatore SEZ',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 2400000,
    },
    created_at: '2023-11-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'emp-007',
    organization_id: 'org-acme-01',
    company_id: 'comp-01',
    company_name: 'Acme Technologies Pvt Ltd',
    branch_id: 'br-blr',
    branch_name: 'Bengaluru Tech Hub',
    department_id: 'dept-hr',
    department_name: 'Human Resources',
    designation_id: 'desig-hradmin',
    designation_title: 'HR Generalist',
    employee_code: 'EMP-1028',
    first_name: 'Sneha',
    last_name: 'Mukherjee',
    work_email: 'sneha.m@acme.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'On Leave',
    employment_type: 'Full Time',
    profile: {
      phone: '+91 93322 11009',
    },
    employment: {
      doj: '2024-05-10',
      reporting_manager_id: 'emp-003',
      reporting_manager_name: 'Arun Kumar',
      notice_period_days: 30,
      work_location: 'Bengaluru Tech Hub',
      shift_name: 'General Shift (09:00 - 18:00)',
      ctc: 1100000,
    },
    created_at: '2024-05-10T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
];

export const initialApprovals: ApprovalItem[] = [
  {
    id: 'appr-101',
    type: 'Leave',
    title: 'Casual Leave Request (2 Days)',
    requested_by_id: 'emp-1024',
    requested_by_name: 'Priya Sharma',
    requested_by_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    details: 'Attending UX Design Summit 2026 in Chennai. Handed off sprint tasks to Rahul.',
    date_submitted: '2026-08-11T09:30:00Z',
    amount_or_duration: '2 Days (14 Aug - 15 Aug)',
    status: 'Pending',
  },
  {
    id: 'appr-102',
    type: 'Expense',
    title: 'Client Travel & Broadband Reimbursement',
    requested_by_id: 'emp-002',
    requested_by_name: 'Rahul Menon',
    requested_by_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    details: 'Flight tickets to Bengaluru client meeting + Q2 broadband bill receipt attached.',
    date_submitted: '2026-08-10T16:15:00Z',
    amount_or_duration: '$240.00',
    status: 'Pending',
  },
  {
    id: 'appr-103',
    type: 'Attendance',
    title: 'Missed Punch Regularization',
    requested_by_id: 'emp-004',
    requested_by_name: 'Ananya Reddy',
    requested_by_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    details: 'Biometric scanner error at Bengaluru Gate 2 on 08-Aug morning.',
    date_submitted: '2026-08-09T11:20:00Z',
    amount_or_duration: '08 Aug 2026',
    status: 'Pending',
  },
  {
    id: 'appr-104',
    type: 'Requisition',
    title: 'Senior Backend Engineer Requisition (2 Positions)',
    requested_by_id: 'emp-001',
    requested_by_name: 'Dharun Joy',
    requested_by_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    details: 'Q3 scaleup requirements for cloud-native microservices team.',
    date_submitted: '2026-08-08T14:00:00Z',
    amount_or_duration: '2 Headcount',
    status: 'Pending',
  },
];

export const initialActivities: ActivityItem[] = [
  {
    id: 'act-1',
    actor_name: 'Priya Sharma',
    actor_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    action: 'submitted a leave request for',
    entity: '14 Aug - 15 Aug',
    timestamp: '2026-08-11T09:30:00Z',
    time_ago: '8 mins ago',
    type: 'leave',
  },
  {
    id: 'act-2',
    actor_name: 'Ananya Reddy',
    actor_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    action: 'joined Engineering team as',
    entity: 'Staff Frontend Engineer',
    timestamp: '2026-08-11T08:45:00Z',
    time_ago: '53 mins ago',
    type: 'employee',
  },
  {
    id: 'act-3',
    actor_name: 'Vikram Srinivasan',
    actor_avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    action: 'completed statutory attendance lock for',
    entity: 'July 2026 Payroll Cycle',
    timestamp: '2026-08-10T18:00:00Z',
    time_ago: 'Yesterday',
    type: 'payroll',
  },
  {
    id: 'act-4',
    actor_name: 'Arun Kumar',
    actor_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action: 'updated POSH & Compliance Audit Log for',
    entity: 'Acme Technologies Coimbatore',
    timestamp: '2026-08-10T14:20:00Z',
    time_ago: 'Yesterday',
    type: 'compliance',
  },
];

export const initialMetrics: DashboardMetrics = {
  total_employees: 428,
  employee_growth_pct: 6.4,
  present_today: 391,
  present_pct: 91.3,
  on_leave_today: 21,
  pending_approvals_count: 27,
  open_requisitions: 14,
  payroll_status: 'Attendance Locked - Ready for Calculation',
  next_payroll_date: '31 Aug 2026',
};
