export type DataScope = 'COMPANY' | 'HR' | 'MANAGER' | 'TEAM' | 'SELF';

export type PrimaryRole =
  | 'Super Admin'
  | 'Company Admin'
  | 'HR Head'
  | 'Manager'
  | 'Team Lead'
  | 'Employee'
  | 'HR Admin'
  | 'Recruiter'
  | 'Payroll Admin'
  | 'Finance'
  | 'Compliance Admin';

export type PermissionAction =
  | 'view'
  | 'create'
  | 'edit'
  | 'delete'
  | 'approve'
  | 'export'
  | 'manage'
  | 'configure';

export type ModuleId =
  | 'dashboard'
  | 'workforce-overview'
  | 'executive-overview'
  | 'my-workspace'
  | 'workspace'
  | 'my-profile'
  | 'profile'
  // People & Core HR
  | 'people'
  | 'employees'
  | 'active-employees'
  | 'probation-employees'
  | 'employee-lifecycle'
  | 'organization'
  | 'departments'
  | 'designations'
  | 'locations'
  | 'vendors'
  | 'organization-vendors'
  | 'documents'
  | 'assets'
  | 'onboarding'
  | 'offboarding'
  // Attendance & Time - Core
  | 'attendance'
  | 'attendance-dashboard'
  | 'attendance-employees'
  | 'employee-attendance'
  | 'history'
  | 'attendance-history'
  | 'ledger'
  | 'regularization'
  | 'exceptions'
  | 'late-early'
  // Shift & Scheduling
  | 'shifts'
  | 'roster'
  | 'shift-calendar'
  | 'policies'
  // Clocking & Devices (Biometric Channel)
  | 'biometric'
  | 'biometric-devices'
  | 'device-enrollment'
  | 'device-sync'
  | 'punch-mapping'
  | 'device-logs'
  // Face Recognition Channel
  | 'face-attendance'
  | 'face-enrollment'
  | 'face-devices'
  | 'face-logs'
  | 'face-exceptions'
  // GPS & Mobile Channel
  | 'gps'
  | 'gps-attendance'
  | 'geofences'
  | 'staff-mapping'
  | 'mobile-clocking'
  | 'location-logs'
  | 'location-exceptions'
  // Work & Overtime
  | 'overtime'
  | 'overtime-requests'
  | 'wfh'
  | 'breaks-workhours'
  // Payroll Inputs
  | 'payroll-inputs'
  | 'payable-days'
  | 'lop-desk'
  | 'ot-pay-inputs'
  | 'payroll-freeze'
  // Audit & Control
  | 'calculation-audit'
  | 'attendance-corrections'
  | 'approval-history'
  | 'attendance-activity-logs'
  | 'time-tracking'
  | 'calendar'
  | 'holidays'
  | 'manual'
  // Leave
  | 'leave'
  | 'leave-dashboard'
  | 'leave-types'
  | 'leave-policies'
  | 'leave-calendar'
  | 'leave-balance'
  | 'leave-requests'
  | 'leave-approval'
  | 'leave-holidays'
  | 'leave-compoff'
  | 'leave-encashment'
  | 'leave-adjustments'
  | 'leave-accrual'
  | 'leave-exceptions'
  | 'leave-reports'
  // Payroll
  | 'payroll'
  | 'payroll-dashboard'
  | 'payroll-salary'
  | 'payroll-processing'
  | 'payroll-earnings'
  | 'payroll-deductions'
  | 'payroll-statutory'
  | 'payroll-documents'
  | 'payroll-fnf'
  | 'payroll-reports'
  | 'payroll-settings'
  // Recruitment & ATS
  | 'recruitment'
  | 'career-dev'
  // Workforce Planning
  | 'workforce-planning'
  // Performance
  | 'performance'
  | 'performance-dashboard'
  | 'performance-goals'
  | 'performance-okr'
  | 'performance-kpi'
  | 'performance-kra'
  | 'performance-cycles'
  | 'performance-reviews'
  | 'performance-ratings'
  | 'performance-development'
  | 'performance-promotion'
  | 'performance-pip'
  | 'performance-reports'
  // Learning & Development
  | 'lms'
  | 'lms-dashboard'
  | 'lms-courses'
  | 'lms-programs'
  | 'lms-calendar'
  | 'lms-enrollment'
  | 'lms-trainers'
  | 'lms-assessments'
  | 'lms-certifications'
  | 'lms-mandatory'
  | 'lms-skills'
  | 'lms-feedback'
  | 'lms-reports'
  | 'lms-settings'
  // Compensation & Benefits
  | 'compensation'
  // Employee Relations
  | 'engagement'
  | 'grievances'
  | 'discipline'
  | 'posh'
  | 'compliance'
  // Travel & Expense
  | 'other-travel'
  // Communication & Help
  | 'helpdesk'
  | 'communication'
  | 'other-communication'
  | 'requests'
  // Analytics & Reports
  | 'analytics'
  | 'analytics-overview'
  | 'analytics-hr'
  | 'analytics-ceo'
  | 'analytics-finance'
  | 'analytics-recruitment'
  | 'analytics-attendance'
  | 'analytics-leave'
  | 'analytics-payroll'
  | 'analytics-performance'
  | 'analytics-training'
  | 'analytics-attrition'
  | 'analytics-workforce'
  | 'analytics-cost'
  | 'analytics-reports'
  | 'analytics-settings'
  | 'workforce-analytics'
  | 'recruitment-analytics'
  | 'attendance-analytics'
  | 'payroll-analytics'
  | 'performance-analytics'
  | 'reports'
  // Automation & Admin
  | 'workflows'
  | 'approvals'
  | 'notifications'
  | 'scheduled-jobs'
  | 'users'
  | 'rbac'
  | 'permissions'
  | 'policies'
  | 'templates'
  | 'integrations'
  | 'security'
  | 'audit-logs'
  | 'settings'
  // Admin sub-modules
  | 'admin-dashboard'
  | 'admin-users'
  | 'admin-roles'
  | 'admin-permissions'
  | 'admin-workflows'
  | 'admin-approvals'
  | 'admin-notifications'
  | 'admin-audit'
  | 'admin-security'
  | 'admin-api'
  | 'admin-integrations'
  | 'admin-subscription'
  | 'admin-billing'
  | 'admin-settings'
  | 'realtime-health'
  | 'admin-realtime-health'
  // ESS (Employee Self-Service) modules
  | 'ess-dashboard'
  | 'ess-attendance'
  | 'ess-leave'
  | 'ess-payroll'
  | 'ess-requests'
  | 'ess-performance'
  | 'ess-learning'
  | 'ess-documents'
  | 'ess-communication'
  | 'ess-profile'
  // TL / Supervisor modules
  | 'tl-dashboard'
  | 'tl-my-team'
  | 'tl-attendance'
  | 'tl-leave'
  | 'tl-approvals'
  | 'tl-tasks'
  | 'tl-performance'
  | 'tl-training'
  | 'tl-communication'
  | 'tl-reports'
  // Platform Admin / SaaS Owner modules
  | 'platform'
  | 'platform-dashboard'
  | 'platform-tenants'
  | 'platform-organizations'
  | 'platform-provisioning'
  | 'platform-tenant-health'
  | 'platform-users'
  | 'platform-staff'
  | 'platform-roles'
  | 'platform-subscriptions'
  | 'platform-plans'
  | 'platform-billing'
  | 'platform-usage'
  | 'platform-features'
  | 'platform-flags'
  | 'platform-marketplace'
  | 'platform-api'
  | 'platform-keys'
  | 'platform-webhooks'
  | 'platform-security'
  | 'platform-sessions'
  | 'platform-operations'
  | 'platform-jobs'
  | 'platform-incidents'
  | 'platform-support'
  | 'platform-audit'
  | 'platform-exports'
  | 'platform-announcements'
  | 'platform-settings'
  // SaaS Business modules
  | 'saas-revenue'
  | 'saas-customers'
  | 'saas-subscriptions'
  | 'saas-churn'
  | 'saas-trials'
  | 'saas-renewals'
  | 'saas-coupons'
  | 'saas-partners'
  | 'saas-[#37]';

export interface ModulePermissionRule {
  moduleId: ModuleId;
  label: string;
  actions: PermissionAction[];
  defaultScope: DataScope;
}

export interface RoleAccessProfile {
  roleName: PrimaryRole;
  hierarchyLevel: number; // 1 = Admin / Super Admin, 2 = HR Head, 3 = Manager, 4 = Team Lead, 5 = Employee
  allowedModules: ModuleId[];
  defaultScope: DataScope;
  moduleScopes: Record<string, DataScope>; // ModuleId -> DataScope override
}

